// Request/response shapes of the search endpoints, taken from the types that
// openapi-typescript generates from the repository's openapi.yaml
// (src/generated/api.d.ts — regenerated by `npm run generate`, never committed).
import type { components } from '../generated/api';

type Schemas = components['schemas'];

export type SearchFileRequest = Schemas['SearchFileRequest'];
export type SearchManyRequest = Schemas['SearchManyRequest'];
export type SearchResponse = Schemas['SearchResponse'];
export type HealthResponse = Schemas['HealthResponse'];
export type ErrorResponse = Schemas['ErrorResponse'];
export type HintRequest = Schemas['Hint'];
