services:
  python:
    build:
      context: .
      dockerfile: python/Dockerfile
    ports:
      - "8007:8007"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512m

  python-base:
    build:
      context: .
      dockerfile: python-base/Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512m

  python-improved:
    build:
      context: .
      dockerfile: python-improved/Dockerfile
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512m

  python-indexed:
    build:
      context: .
      dockerfile: python-indexed/Dockerfile
    ports:
      - "8005:8005"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512m

  java:
    build:
      context: .
      dockerfile: java/Dockerfile
    ports:
      - "8002:8002"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512m

  go:
    build:
      context: .
      dockerfile: go/Dockerfile
    ports:
      - "8003:8003"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512m

  cpp:
    build:
      context: .
      dockerfile: cpp/Dockerfile
    ports:
      - "8004:8004"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512m

  nest:
    build:
      context: .
      dockerfile: nest/Dockerfile
    ports:
      - "8006:8006"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512m

