//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Human-readable reason the request was rejected.
	//
	// Example: letters and hints cannot both be empty
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Always `ok` when the service is up.
	//
	// Example: ok
	Status string `json:"status"`
}

// Hint Positional constraint on a word.
type Hint struct {
	// Excluded When true, `letter` must NOT appear at `position`.
	Excluded bool `json:"excluded,omitempty"`

	// Letter Expected letter at `position`. Null or absent means no letter constraint (only the position matters).
	//
	//
	// Example: e
	Letter string `json:"letter,omitempty"`

	// Position 1-indexed position of the constraint in the word.
	//
	// Example: 3
	Position int `json:"position"`
}

// SearchFileRequest Search for words of one fixed length.
type SearchFileRequest struct {
	// Hints Positional constraints, applied after the letter-pool filter.
	Hints []Hint `json:"hints,omitempty"`

	// Lang Language code — selects the dictionary to search.
	//
	// Example: fr
	Lang string `json:"lang,omitempty"`

	// Letters Available letters, one character per element. Empty means no letter-pool constraint (only hints filter).
	//
	//
	// Example: ["a","e","r","s","t"]
	Letters []string `json:"letters,omitempty"`

	// Strict When true, each element of `letters` may only be used once (Scrabble-style).
	Strict bool `json:"strict,omitempty"`

	// WordLength Exact word length to search for.
	//
	// Example: 5
	WordLength int `json:"wordLength"`
}

// SearchManyRequest Search for words of every length up to the number of letters.
type SearchManyRequest struct {
	// Hints Positional constraints, applied to every length scanned.
	Hints []Hint `json:"hints,omitempty"`

	// Lang Language code — selects the dictionary to search.
	//
	// Example: fr
	Lang string `json:"lang,omitempty"`

	// Letters Available letters as a single string. The longest word searched has as many characters as `letters`; every shorter length is scanned too.
	//
	//
	// Example: artes
	Letters string `json:"letters"`
}

// SearchResponse Word search result.
type SearchResponse struct {
	// Count Number of matching words (the length of `words`).
	Count int `json:"count"`

	// Words Matching words in scan order (longest-first for /search/many).
	Words []string `json:"words"`
}

// SearchFileJSONRequestBody defines body for SearchFile for application/json ContentType.
type SearchFileJSONRequestBody = SearchFileRequest

// SearchManyJSONRequestBody defines body for SearchMany for application/json ContentType.
type SearchManyJSONRequestBody = SearchManyRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health Liveness check
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
	// SearchFile Search words of a fixed length
	// (POST /search/file)
	SearchFile(w http.ResponseWriter, r *http.Request)
	// SearchMany Search words across all lengths
	// (POST /search/many)
	SearchMany(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchFile operation middleware
func (siw *ServerInterfaceWrapper) SearchFile(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchFile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchMany operation middleware
func (siw *ServerInterfaceWrapper) SearchMany(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchMany(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.Health)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/search/file", wrapper.SearchFile)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/search/many", wrapper.SearchMany)

	return m
}
